name: Сообщить о баге / Report a Bug
description: Нашли проблему на CSLAND.FUN? Расскажите нам 🙂
labels:
  - pending
title: "[BUG] Краткое описание проблемы / Short description"
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что помогаете улучшать CSLAND.FUN ❤️  
        Thank you for helping improve CSLAND.FUN ❤️

  - type: textarea
    id: what
    attributes:
      label: Что случилось? / What happened?
      description: Опишите проблему простыми словами
      placeholder: Например: открываю профиль — страница зависает
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Как повторить? / How to reproduce?
      placeholder: |
        1. Открываю сайт
        2. Захожу в ...
        3. Нажимаю ...
        4. Баг
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Что ожидали? / Expected behavior
    validations:
      required: true

  - type: input
    id: where
    attributes:
      label: Где это произошло? / Where on site?
      placeholder: Профиль / Магазин / Главная и т.д.

  - type: dropdown
    id: device
    attributes:
      label: Устройство / Device
      options:
        - ПК
        - Телефон
        - Планшет
        - Другое

  - type: input
    id: browser
    attributes:
      label: Браузер / Browser
      placeholder: Chrome / Firefox / Safari …

  - type: textarea
    id: media
    attributes:
      label: Скриншот или видео / Screenshot or video
      description: Если можете — приложите ссылку

  - type: textarea
    id: more
    attributes:
      label: Дополнительно / Extra
